### ISSUE TITLE
Failed to install rzmq

### ISSUE THREAD

**Issue by jiaweih** [IRkernel/IRkernel#50]
System: OS X Yosemite, R: @3.1.2_0+accelerate+cairo+gfortran48+recommended+x11

```
> install_github('armstrtw/rzmq')
Downloading github repo armstrtw/rzmq@master
Installing rzmq
'/opt/local/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD  \
  INSTALL  \
  '/private/var/folders/rv/wstf88ns4g16sqgg62lsz_pw0000gn/T/Rtmp5NeM5l/devtools182a058697683/armstrtw-rzmq-320891d'  \
  --library='/Users/jiaweihe/Library/R/3.1/library' --install-tests 
 installing *source* package ‘rzmq’ ...
** libs
/usr/bin/clang++ -std=c++11 -I/opt/local/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../inst/cppzmq -I/opt/local/include    -fPIC  -pipe -Os -arch x86_64 -stdlib=libc++ -c interface.cpp -o interface.o
interface.cpp:24:10: **fatal error: 'zmq.hpp' file not found**
#include <zmq.hpp>
         ^
1 error generated.
make: *** [interface.o] Error 1
ERROR: compilation failed for package ‘rzmq’
 removing ‘/Users/jiaweihe/Library/R/3.1/library/rzmq’
```
Error: Command failed (1)

**Comment by JanSchulz** [comment]
This could also be a problem in install_github as the above file is actually included via a submodule.

**Comment by takluyver** [comment]
Good point - if `install_github()` works by downloading a tarball/zipball from Github, any submodules will be left out.

**Comment by everm1nd** [comment]
I have the same issue. `brew install czmq zmq` have no result.

**Comment by armaneshaghi** [comment]
Same here, `brew install czmq zmq` does not work.

**Comment by armaneshaghi** [comment]
This solve my issue:

From terminal:

`https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp`

`mv zmq.hpp /usr/local/include/`

From inside R:

`require('devtools')`

`install_github('armstrtw/rzmq'`

**Comment by everm1nd** [comment]
@armaneshaghi it works! thanks! :+1:

**Comment by cosinequanon** [comment]
You can also install rzmq from CRAN which does not seem to have any of these issues.

**Comment by ellisonbg** [comment]
I am seeing this as well, and there is no rzmq on CRAN for 3.1.2. This basically makes the R kernel unusable on a Mac with homebrew right now (it used to work fine). Looks like we will have to create a cppzmq package for brew. We definitely need to fix this before the 3.0 release and post working instructions for the R kernel on the main ipython install page.

**Comment by ellisonbg** [comment]
I should note that the manual install of the `zmq.hpp` header did fix it, but I don't think we can recommend that to users.

**Comment by armaneshaghi** [comment]
or perhaps a work-around is to force `install_github` to include submodules.

**Comment by JanSchulz** [comment]
Why not simply include the file? The Sqlite package includes the complete sqlite source, so...

**Comment by cosinequanon** [comment]
@ellisonbg I was able to get rzmq for 3.1.2. but I compiled from source. I think the issue is here: http://cran.us.r-project.org/.

**Comment by merqurio** [comment]
@armaneshaghi Thanks for the tip !! :+1:

**Comment by carloshgaray** [comment]
+1 for @armaneshaghi . Gracias

**Comment by ellisonbg** [comment]
@cosinequanon can you clarify what exact steps you took to get it working?

**Comment by cosinequanon** [comment]
I compiled R 3.1.2 from source on my mac and then was able to install the package directly from CRAN.

**Comment by ccwang002** [comment]
Thanks for @armaneshaghi 's idea, I managed to compile it on Yosemite with brewed R by separating the git clone and installation steps since `install_github` doesn't support git submodule.

```bash
# manually git clone the rzmq repo
$ git clone https://github.com/armstrtw/rzmq.git --recursive 

# install through install_local()
$ R
> library(devtools)
> install_local('./rzmq')
```

Hope that helps :)

**Comment by gdequeiroz** [comment]
I tried all the above without success. When I run:

```
> install_github("takluyver/IRkernel")
```
I get this:

```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  namespace ‘rzmq’ 0.6.8 is being loaded, but >= 0.7.0 is required
ERROR: lazy loading failed for package ‘IRkernel’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/IRkernel’
```

**Comment by rgbkrk** [comment]
@gdequeiroz I'm completely new to R's packaging system, but is that an error message stating that rzmq is out of date? Maybe we can run `install_github('armstrtw/rzmq');` first?

**Comment by rgbkrk** [comment]
Not seeing any direct upgrade options at quick glance on devtools. :unamused:

**Comment by OrganicIrradiation** [comment]
I am having the same issue with Mac OS X 10.10.2.

Starting with a fresh install of Homebrew, I installed python, python3, r, and zmq installed in bash:

brew install python python3 r zeromq
I am trying to install IRkernel, which requires that rzmq be installed. However, I get a fatal error with "'zmq.h' file not found" when I run the following in R:
```
install.packages("devtools")
install.packages('RCurl')
library(devtools)
install_github('armstrtw/rzmq')
```

I've also tried:
```
# manually git clone the rzmq repo
$ git clone https://github.com/armstrtw/rzmq.git --recursive 

# install through install_local()
$ R
> library(devtools)
> install_local('./rzmq')
```

To no avail.

**Comment by michaelpacer** [comment]
Hi — following @ccwang002's solution of recursively downloading it locally and then installing it worked for me. @OrganicIrradiation what were the errors that you ran into. Have you been able to successfully install the devtools? 

To check, I just brewed `r`  anew (rather than from their `pkg` installer on their website which was my previous incarnation) and I did not include zeromq in that install. I doubt that that could be what is causing your issues, but I figure its the only major difference I can see without being able to see the errors that are raised.

**Comment by OrganicIrradiation** [comment]
@michaelpacer I tried @ccwang002's solution. And keep getting the same error (regardless of whether I try to install_local with the locally cloned copy or if I use the CRAN mirror).  I also have done a ```brew install r --build-from-source```.

Here is the output with ```install.packages('rzmq')```:
```
> install.packages('rzmq')
trying URL 'http://cran.rstudio.com/src/contrib/rzmq_0.7.7.tar.gz'
Content type 'application/x-gzip' length 16246 bytes (15 Kb)
opened URL
==================================================
downloaded 15 Kb

* installing *source* package ‘rzmq’ ...
** package ‘rzmq’ successfully unpacked and MD5 sums checked
** libs
clang++ -std=c++11 -I/usr/local/Cellar/r/3.1.2_1/R.framework/Resources/include -DNDEBUG -I../inst/cppzmq -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -fPIC -D__ACCELERATE__ -c interface.cpp -o interface.o
interface.cpp:22:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
^
1 error generated.
make: *** [interface.o] Error 1
ERROR: compilation failed for package ‘rzmq’
* removing ‘/usr/local/Cellar/r/3.1.2_1/R.framework/Versions/3.1/Resources/library/rzmq’

The downloaded source packages are in
‘/private/var/folders/_r/7xdg4v39247_259q1qjjktbc0000gn/T/Rtmpcc2gyE/downloaded_packages’
Warning message:
In install.packages("rzmq") :
installation of package ‘rzmq’ had non-zero exit status
```

Here is the output with ```library(devtools)``` and ```install_github('armstrtw/rzmq')```:
```
> library(devtools)
> install_github('armstrtw/rzmq')
Downloading github repo armstrtw/rzmq@master
Installing rzmq
'/usr/local/Cellar/r/3.1.2_1/R.framework/Resources/bin/R' --vanilla CMD \
INSTALL \
'/private/var/folders/_r/7xdg4v39247_259q1qjjktbc0000gn/T/Rtmpc2mGvD/devtools10f0d7f8d4715/armstrtw-rzmq-320891d' \
--library='/usr/local/Cellar/r/3.1.2_1/R.framework/Versions/3.1/Resources/library' \
--install-tests 

* installing *source* package ‘rzmq’ ...
** libs
clang++ -std=c++11 -I/usr/local/Cellar/r/3.1.2_1/R.framework/Resources/include -DNDEBUG -I../inst/cppzmq -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -fPIC -D__ACCELERATE__ -c interface.cpp -o interface.o
interface.cpp:22:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
^
1 error generated.
make: *** [interface.o] Error 1
ERROR: compilation failed for package ‘rzmq’
* removing ‘/usr/local/Cellar/r/3.1.2_1/R.framework/Versions/3.1/Resources/library/rzmq’
Error: Command failed (1)
```

**Comment by ccwang002** [comment]
Could you try to output your cpp header search paths by 
```bash
$ clang++ -E -x c++ - -v < /dev/null
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
# ...
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
 /usr/local/include
# ...

$ ls -l /usr/local/include/zmq.h
/usr/local/include/zmq.h -> ../Cellar/zeromq/4.0.5_2/include/zmq.h
```
You should find `/usr/local/include` in the search path and `zmq.h` under that folder.


Adding `-v` at the following line in `rzmq/src/Makevars` 
```
PKG_CPPFLAGS = -I../inst/cppzmq   # add -v here
```
will show the search path during `install_local(...)`. Sorry I didn't figure out how to use the more proper `install_local(args='...')` way to pass the verbosity flag.

**Comment by ellisonbg** [comment]
I think the solution is to create a brew package for zmqcpp.

On Tue, Mar 3, 2015 at 8:59 AM, Liang Bo Wang <notifications@github.com>
wrote:

> Could you try to output your cpp header search paths by
>
> $ clang++ -E -x c++ - -v < /dev/null
> Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)# ...#include "..." search starts here:#include <...> search starts here:
>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
>  /usr/local/include# ...
>
> $ ls -l /usr/local/include/zmq.h
> /usr/local/include/zmq.h -> ../Cellar/zeromq/4.0.5_2/include/zmq.h
>
> You should find /usr/local/include in the search path and zmq.h under
> that folder.
>
> Adding -v at the following line in rzmq/src/Makevars
>
> PKG_CPPFLAGS = -I../inst/cppzmq   # add -v here
>
> will show the search path during install_local(...). Sorry I didn't
> figure out how to use the more proper install_local(args='...') way to
> pass the verbosity flag.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/takluyver/IRkernel/issues/50#issuecomment-76986177>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by OrganicIrradiation** [comment]
@ccwang002 Here are the search header info and library info:
```
$ clang++ -E -x c++ - -v < /dev/null
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
#include "..." search starts here:
#include <...> search starts here:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/include
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks (framework directory)
End of search list.

$ ls -l /usr/local/include/zmq.h
/usr/local/include/zmq.h -> ../Cellar/zeromq/4.0.5_2/include/zmq.h
```

So it looks like I needed to install the xcode command line tools to get /usr/local/include into the clang++ search path (not sure why the command line tools were not already installed on this computer).  I ran ```xcode-select --install``` and **TADA!** installation of rzmq worked and I was able to get IRkernel up and running. Thanks for all of your help!

@ellisonbg There is a homebrew tap that has cppzmq:
```
$ brew tap bertjwregeer/compat
$ brew install cppzmq
```
This did not fix my issue though, it looks like only the installation of ```zeromq``` was necessary (along with the xcode command line tools).

Just to summarize, here were the steps necessary to get IRkernel setup on this machine:
```
# Install Xcode Command Line Tools if not already installed
$ xcode-select --install

# Install python, r, and zmq via homebrew
$ brew install python python3 r zeromq

# Install iPython/Jupyter
$ pip install ipython[all]

# Install IRkernel
$ r
> install.packages("devtools")
> install.packages('rzmq')
# Need RCurl for install_github
> install.packages('RCurl')
> library(devtools)
> install_github("takluyver/IRdisplay")
> install_github("takluyver/IRkernel")
# Only if you have IPython 3 or above installed:
> IRkernel::installspec()
```

**Comment by ellisonbg** [comment]
Hmm, this explanation doesn't match up with what other's have found. I had
XCode command line tools installed, but it didn't work until I installed
the zmpcpp header.

On Wed, Mar 4, 2015 at 2:04 AM, OrganicIrradiation <notifications@github.com
> wrote:

> @ccwang002 <https://github.com/ccwang002> Here are the search header info
> and library info:
>
> $ clang++ -E -x c++ - -v < /dev/null
> Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
> #include "..." search starts here:
> #include <...> search starts here:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/include
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks (framework directory)
> End of search list.
>
> $ ls -l /usr/local/include/zmq.h
> /usr/local/include/zmq.h -> ../Cellar/zeromq/4.0.5_2/include/zmq.h
>
> So it looks like I needed to install the xcode command line tools to get
> /usr/local/include into the clang++ search path (not sure why the command
> line tools were not already installed on this computer). I ran xcode-select
> --install and *TADA!* installation of rzmq worked and I was able to get
> IRkernel up and running. Thanks for all of your help!
>
> @ellisonbg <https://github.com/ellisonbg> There is a homebrew tap that
> has cppzmq:
>
> $ brew tap bertjwregeer/compat
> $ brew install cppzmq
>
> This did not fix my issue though, it looks like only the installation of
> zeromq was necessary (along with the xcode command line tools).
>
> Just to summarize, here were the steps necessary to get IRkernel setup on
> this machine:
>
> # Install Xcode Command Line Tools if not already installed
> $ xcode-select --install
>
> # Install python, r, and zmq via homebrew
> $ brew install python python3 r zeromq
>
> # Install iPython/Jupyter
> $ pip install ipython[all]
>
> # Install IRkernel
> $ r
> > install.packages("devtools")
> > install.packages('rzmq')
> # Need RCurl for install_github
> > install.packages('RCurl')
> > library(devtools)
> > install_github("takluyver/IRdisplay")
> > install_github("takluyver/IRkernel")
> # Only if you have IPython 3 or above installed:
> > IRkernel::installspec()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/takluyver/IRkernel/issues/50#issuecomment-77127993>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ccwang002** [comment]
To be clear, `zmq.h` not found and `zmq.hpp` not found are different situations. 

For `zmq.h`, it's probably due to the installation of the normal zeromq library. 

For `zmq.hpp`, since you can see the compiler looking for headers under `-I../inst/cppzmq` during the compilation, if the git repo is fully cloned, the compiler should always find it.

**Comment by ellisonbg** [comment]
Ahh, thanks! As we find solutions for these things, can someone update the
README for the IRkernel so other users will have it easier?

On Wed, Mar 4, 2015 at 9:09 AM, Liang Bo Wang <notifications@github.com>
wrote:

> To be clear, zmq.h not found and zmq.hpp not found are different
> situations.
>
> For zmq.h, it's probably due to the installation of the normal zeromq
> library.
>
> For zmq.hpp, since you can see the compiler looking for headers under
> -I../inst/cppzmq during the compilation, if the git repo is fully cloned,
> the compiler should always find it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/takluyver/IRkernel/issues/50#issuecomment-77199916>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by takluyver** [comment]
Anyone having trouble installing this: you might like to try [r2_kernel](https://github.com/takluyver/r2_kernel), an experimental alternative approach using rpy2 to drive R. This might be easier to install.

**Comment by ellisonbg** [comment]
Nice! But I do think that in the long run, the native R kernel is
absolutely critical.

On Wed, Mar 4, 2015 at 2:33 PM, Thomas Kluyver <notifications@github.com>
wrote:

> Anyone having trouble installing this: you might like to try r2_kernel
> <https://github.com/takluyver/r2_kernel>, an experimental alternative
> approach using rpy2 to drive R. This might be easier to install.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/takluyver/IRkernel/issues/50#issuecomment-77265146>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by takluyver** [comment]
I don't know that it is. Python is a much, much nicer language to write the kind of infrastructure that a kernel needs - (de)serialisation and messaging. The idea of having a native kernel was that R programmers would be involved with developing it, but as we discussed on Friday, there's a substantial overlap between R and Python programmers. So I don't think there's a reason why it can't be developed in Python by people who care about R.

For the time being, I intend to keep both alive and see what happens.

**Comment by ellisonbg** [comment]
Personally, I completely agree with your statement that Python is a much
better language for this type of thing. But, in the long run, if we want
this to be used, accepted, adopted and maintained by the the R community it
has to be native R code. Also, there are some kernel features (Comms and
Widgets) that I think will be easier to write natively than trying to proxy
through rpy2.

On Wed, Mar 4, 2015 at 2:51 PM, Thomas Kluyver <notifications@github.com>
wrote:

> I don't know that it is. Python is a much, much nicer language to write
> the kind of infrastructure that a kernel needs - (de)serialisation and
> messaging. The idea of having a native kernel was that R programmers would
> be involved with developing it, but as we discussed on Friday, there's a
> substantial overlap between R and Python programmers. So I don't think
> there's a reason why it can't be developed in Python by people who care
> about R.
>
> For the time being, I intend to keep both alive and see what happens.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/takluyver/IRkernel/issues/50#issuecomment-77268146>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by takluyver** [comment]
I'm not sure that that assertion is warranted. The 'R community' is not a distinct thing, there are plenty of programmers who do both R and Python. And if having a Python layer makes it easier to maintain, I don't see any reason to avoid that.

r2_kernel is not pure Python - a fair component of the guts is still in R, it's really just using Python to deal with the messaging protocol.

I'm not sure what a good interface to widgets/comms in R would be, but whatever it is, I don't think there should be any great obstacle to doing it via rpy2. Ultimately, you just need an interface to send and receive messages, which is what we use for the kernel in general, and that's perfectly possible.

**Comment by dennisobrien** [comment]
I had this same issue on Ubuntu 14.04 using R 3.0.2 (the version that is included in the standard packages).  It was fixed by adding my local CRAN repository to sources.list and installing R 3.1.2.

A similar issue was mentioned in the github project armstrtw/rzmq regarding the `CXX1XSTD` flag missing from `/etc/R/Makevars`.

**Comment by pylang** [comment]
@armaneshaghi's solution fixed the first issue - "header missing" error after install_github('armstrtw/rzmq').  Now I get:
```
Downloading github repo armstrtw/rzmq@master
Installing rzmq
"C:/PROGRA~1/R/R-31~1.2/bin/x64/R" --vanilla CMD INSTALL  \
  "~/AppData/Local/Temp/RtmpIhAeOL/devtools1efc4ce53fcd/armstrtw-rzmq-45f0d94"  \
  --library="C:/Anaconda/Lib/site-packages/rpy2/R/win-library/3.1"  \
  --install-tests 

* installing *source* package 'rzmq' ...
** libs
g++ -m64 -std=c++0x -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -I../inst/cppzmq    -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c interface.cpp -o interface.o
interface.cpp:22:17: fatal error: zmq.h: No such file or directory
compilation terminated.
make: *** [interface.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-31~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="rzmq.dll" WIN=64 TCLBIN=64 OBJECTS="interface.o"' had status 2
ERROR: compilation failed for package 'rzmq'
* removing 'C:/Anaconda/Lib/site-packages/rpy2/R/win-library/3.1/rzmq'
Error: Command failed (1)
```
[Win7-64, Anaconda, python2 (default), python3 (virtualenv), IPython3, R3.1.2, Rtools 3.1, ZeroMQ-4.0.4 rc]

**Comment by fperez** [comment]
Given the dubious state of maintenance of rpy2 (its status on Windows and OSX is tenuous at best), having a native R kernel is *critical* for us.  rpy2 is a complex project straining without enough developers, relying on that for something as important as R across platforms is not a good idea.

Interestingly, I'm seeing on OSX an error that hasn't been reported before. I continue to investigate, but reporting here in case someone else sees it:

```
installing to /usr/local/Cellar/r/3.1.3/R.framework/Versions/3.1/Resources/library/rzmq/libs
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/Cellar/r/3.1.3/R.framework/Versions/3.1/Resources/library/rzmq/libs/rzmq.so':
  dlopen(/usr/local/Cellar/r/3.1.3/R.framework/Versions/3.1/Resources/library/rzmq/libs/rzmq.so, 6): Library not loaded: libzmq.3.dylib
  Referenced from: /usr/local/Cellar/r/3.1.3/R.framework/Versions/3.1/Resources/library/rzmq/libs/rzmq.so
  Reason: image not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/Cellar/r/3.1.3/R.framework/Versions/3.1/Resources/library/rzmq’
Error: Command failed (1)
```

**Comment by fperez** [comment]
OK, in case anyone stumbles on this, the problem was an odd interaction between homebrew and conda. I'd set up my conda install as a valid system prefix (for `--prefix` installations of other tools), so the conda libs became visible to homebrew. That seems to be a bad idea, I guess.

I'm new to OS X and just figuring out how to make conda and homebrew play nice, so I obviously stepped on a land mine here.

Still, we do need to make this install an easier one in the long run.  A first-class R experience is too important in the long run for the project.

**Comment by pylang** [comment]
Agreed.  Despite getting the experimental [r2_kernel to successfully work](https://github.com/takluyver/r2_kernel/issues/3#event-249467796) instead (thanks to @takluyver), in the long run I'd favor a more stable integration with R, simply in dealing with rpy2 issues in the past.  

At minimum, it makes sense to reduce the installation barriers for IJulia, Python 3 and R from which Jupyter gets its name.  However, from my experience, it's been an effort, and I imagine installing the present kernels could be an enduring challenge for many users.  In the future,  an intuitive method, e.g. maybe `pip install ipython --fooKernel`, would be ideal.  Thanks for your great work.

**Comment by ccwang002** [comment]
@pylang you could find more windows-related solution at #54.

**Comment by smartinsightsfromdata** [comment]
As requested, this is my experience.  I use a MacBook Pro with Yosemite 10.10.3 &
R 3.13.
I followed the instructions in the README:
- used brew to download: ```brew install zmq```
- got the error on compiling ```rzmq```:   ```zmq.hpp missing```  (Please note I consider good practice compile all R packages: it tell me in advance of problems I will have down the line).
- Discovered I (may) need installing ```czmq```.  Installed with ```brew install czmq```
- Still got the error  ```zmq.hpp missing```.  Instructions (above I believe) suggest using wget, obviously not available on OSX.  Used instead
```curl "https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp" -o "zmq.hpp"``` then moved the file to ```/usr/local/include/``` as suggested.
- I wanted to use Python 3 (I have Anaconda installed but normally I use 2.7 - a little). Removed conda 2.7 and re-installed conda3.
- Eagerly try: ```IRkernel::installspec()``` in the R console in RStudio but I get:
```
sh: ipython: command not found
```
After a bit of head scratching, I thought the instruction referred to R console. Tried the same in R console. I got:
```
IRkernel::installspec()
/bin/sh: ipython: command not found
```
After more head scratching I had the idea of trying R directly at the command line (please note this is not RHEL / Ubuntu: I never use R at the command line in OSX).
```
success!!
```
Can somebody come with a clearer README please?
Also, while I've used ipython in the past, I just come across jupyter and the concept of a R kernel.  Do you have a wiki that explains what is an R kernel exactly? does it use magic or something less pythonesque?

**Comment by kouichi-c-nakamura** [comment]
@smartinsightsfromdata Thanks a lot! I also had the  `/bin/sh: ipython: command not found` error. But thanks to you, now I have the "R" option in addition to "Python 2" for New > Notebooks in Jupyter. Here's my eintire log (Yosemite 10.10.3, Anaconda 3.10.1).

    $ brew install zmq
    $ brew update
    $ brew upgrade zmq

    $ export CPATH=/usr/local/include  # maybe not necessary
    $ export LIBRARY_PATH=/usr/local/lib # maybe not necessary

Then in R console in R app.

    > install.packages("devtools")
    > install.packages('RCurl')
    > library(devtools)

Because I had an error at `install_github('armstrtw/rzmq')`, I looked at [this page](https://github.com/IRkernel/IRkernel/issues/50) and followed @armaneshaghi. In the terminal again:

    $ wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp
    $ mv zmq.hpp /usr/local/include/

Again in R console

    > require('devtools')
    > install_github('armstrtw/rzmq')
    > install_github('IRkernel/repr')

    ERROR: this R is version 3.1.1, package 'repr' requires R >= 3.1.3
    Error: Command failed (1)

So I updated the R version to 3.1.3

    > require('devtools')
    > install_github('IRkernel/repr')
    > install_github('IRkernel/IRdisplay')
    > install_github('IRkernel/IRkernel')

Finally, in the terminal:

    $ R
    > IRkernel::installspec()

DONE. Bloody hell! :)

**Comment by kouichi-c-nakamura** [comment]
I'm trying to reproduce the above method on another Mac (Yosemite 10.10.3, conda 3.10.1) but at `install_github('IRkernel/repr')` I've got the same error as @fperez reported above.

```
> install_github('IRkernel/repr')
Downloading github repo IRkernel/repr@master
Installing repr
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/pb/3x0t4btd70z34pnl8tk667ph0000gn/T/RtmpqaICvG/devtools1ab579c392fe/IRkernel-repr-7b22bc2'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'  \
  --install-tests 

* installing *source* package ‘repr’ ...
** R
** preparing package for lazy loading
** help
No man pages found in package  ‘repr’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded
Warning: S3 methods ‘repr_html.repr’, ‘repr_javascript.repr’, ‘repr_jpg.repr’, ‘repr_json.repr’, ‘repr_latex.repr’, ‘repr_markdown.repr’, ‘repr_pdf.repr’, ‘repr_png.repr’, ‘repr_svg.repr’, ‘repr_text.repr’ were declared in NAMESPACE but not found
Error in namespaceExport(ns, exports) : undefined exports: repr.format
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/repr’
Error: Command failed (1)
```

**Comment by takluyver** [comment]
@kouichi-c-nakamura that's a different error, see IRkernel/repr#2. It should now be fixed, so try again.

**Comment by kouichi-c-nakamura** [comment]
@takluyver Thanks a lot! It works now.

**Comment by JanSchulz** [comment]
Can someone on a mac check if this works "out of the box" on Mac OSX?

```
install.packages(c("rzmq","repr","IRkernel","IRdisplay"), repos="http://irkernel.github.io/", type="source")
```

There are source packages which IMO should have all files necessary to install the package but I have no linux/mac to test it...

**Comment by takluyver** [comment]
I tried on Linux *without* `type='source'`, and it mostly seemed to work fine, except that `repr` appears to require a slightly newer R version than I have.

@flying-sheep , is there a reason repr actually requires 3.1.3? I have 3.1.1. If not, can we tweak the required R version in DESCRIPTION to something appropriate. IRkernel and IRdisplay both specify >=3.0.1.

**Comment by flying-sheep** [comment]
no, there’s not, that was the default. go ahead and change it :)

**Comment by takluyver** [comment]
Thanks, done

**Comment by JanSchulz** [comment]
@takluyver as far as I know linux defaults to `type='source'` per default, so that is not required. On windows it defaults to binary and they are included in the repo. I just don't know what OSX does :-/

**Comment by takluyver** [comment]
Hopefully one of the Mac users will enlighten us both :)

**Comment by JanSchulz** [comment]
The main part is done here. What IMO needs to be done is getting rzmq to build under install_github, which AFAIK fails due to the submodule. But IMO thats a bug in rzmq (https://github.com/armstrtw/rzmq/issues/15)

**Comment by takluyver** [comment]
OK, closing this in the hope that the repo we provide will solve these issues.

**Comment by xiaoweiz** [comment]
Just to be clear, `rzmq` must be built from source, correct? On OSX with R 3.2, I tried `install.packages('rzmq', repos = 'http://irkernel.github.io/')` and got 
```R
Warning: unable to access index for repository http://irkernel.github.io/bin/macosx/mavericks/contrib/3.2
Package which is only available in source form, and may need
  compilation of C/C++/Fortran: ‘rzmq’
Do you want to attempt to install these from sources?
```
and continuing further led to 
```
installing the source package ‘rzmq’

trying URL 'http://irkernel.github.io/src/contrib/rzmq_0.7.7.tar.gz'
Content type 'application/octet-stream' length 897372 bytes (876 KB)
==================================================
downloaded 876 KB

* installing *source* package ‘rzmq’ ...
** libs
clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include    -I../inst/cppzmq -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2 -c interface.cpp -o interface.o
interface.cpp:22:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
         ^
1 error generated.
make: *** [interface.o] Error 1
ERROR: compilation failed for package ‘rzmq’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq’

The downloaded source packages are in
	‘/private/var/folders/qt/mlwd3rvn26v0ydgk4yvm21jm0000gn/T/RtmphSc8jc/downloaded_packages’
Warning message:
In install.packages("rzmq", repos = "http://irkernel.github.io/") :
  installation of package ‘rzmq’ had non-zero exit status
```

**Comment by flying-sheep** [comment]
well, it’s at

http://irkernel.github.io/bin/macosx/contrib/3.2, not

http://irkernel.github.io/bin/macosx/mavericks/contrib/3.2

so we probably need to fix that.

**Comment by xiaoweiz** [comment]
No, still looking for `http://irkernel.github.io/bin/macosx/mavericks/contrib/3.2`

**Comment by flying-sheep** [comment]
hmm, that’s OK: i tried to make this URL work, too, but it appears that GH pages doesn’t support symlinks!

so until we figure out a way to fix this, you could try to install the ZMQ headers [as described here](http://irkernel.github.io/#installing-from-source-default-on-linux-but-possible-on-all-platforms)

**Comment by flying-sheep** [comment]
hey, @xiaoweiz, please try `install.packages(c('rzmq','repr','IRkernel','IRdisplay'), repos = 'https://irkernel.github.io/', type = 'mac.binary')`

**Comment by xiaoweiz** [comment]
It's OK for `rzmq`: 
```R
install.packages('rzmq', repos = 'http://irkernel.github.io/', type = 'mac.binary')
trying URL 'http://irkernel.github.io/bin/macosx/contrib/3.2/rzmq_0.7.7.tgz'
Content type 'application/octet-stream' length 81898 bytes (79 KB)
==================================================
downloaded 79 KB


The downloaded binary packages are in
	/var/folders/qt/mlwd3rvn26v0ydgk4yvm21jm0000gn/T//RtmpjQTXpd/downloaded_packages
```
but not for the others:
```R
install.packages(c('repr','IRkernel','IRdisplay'), repos = 'https://irkernel.github.io/')
Warning: unable to access index for repository https://irkernel.github.io/src/contrib
Warning: unable to access index for repository https://irkernel.github.io/bin/macosx/mavericks/contrib/3.2
Warning message:
packages ‘repr’, ‘IRkernel’, ‘IRdisplay’ are not available (for R version 3.2.0)
```

**Comment by JanSchulz** [comment]
Damn, this is my fault, I only added one path to drat...

Not sure how to find out where to put binaries: http://cran.r-project.org/doc/manuals/R-admin.html#OS-X-packages and http://cran.r-project.org/doc/manuals/R-admin.html#Setting-up-a-package-repository says that it depends on compilers, so installing these packages in on wrong system will not be good :-(

**Comment by flying-sheep** [comment]
well, let’s see if it works for him.

@xiaoweiz you can install those from source, as they don’t need compileage: `install.packages(c('repr','IRkernel','IRdisplay'), repos = 'https://irkernel.github.io/', type='source')`

if something crashes, you need to install `rzmq` from source as well by first installing the headers as described under “Homebrew” or “MacPorts” [here](http://irkernel.github.io/#zmq)

**Comment by JanSchulz** [comment]
@xiaoweiz can you give me the output of 
```
> .Platform$pkgType
[1] "win.binary"
> getOption("pkgType")
[1] "both"
> getOption("repos")
                                CRAN                            CRANextra 
          "http://cran.rstudio.com/" "http://www.stats.ox.ac.uk/pub/RWin" 
attr(,"RStudio")
[1] TRUE
> contrib.url(getOption("repos"), getOption("pkgType"))
[1] "http://cran.rstudio.com/src/contrib"            "http://www.stats.ox.ac.uk/pub/RWin/src/contrib"
```

**Comment by JanSchulz** [comment]
@flying-sheep I think it should work as I think our packages are build on the maverics+ macosx system, but this should be fixed in drat, so I have to put in a check/switch there...

**Comment by flying-sheep** [comment]
so remove support for OSX 10.8 and smaller by simply moving the files?

**Comment by flying-sheep** [comment]
@JanSchulz like this? (#8)

**Comment by xiaoweiz** [comment]
@JanSchulz 
```R
> .Platform$pkgType
[1] "mac.binary.mavericks"
> getOption("pkgType")
[1] "both"
> getOption("repos")
                     CRAN 
"http://cran.rstudio.com" 
attr(,"RStudio")
[1] TRUE
> contrib.url(getOption("repos"), getOption("pkgType"))
[1] "http://cran.rstudio.com/src/contrib"
> contrib.url(getOption("repos"), .Platform$pkgType)
[1] "http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.2"
```

**Comment by flying-sheep** [comment]
@JanSchulz yeah, drat doesn’t handle `mac.binary.mavericks`: eddelbuettel/drat#20

@xiaoweiz i moved the packages, so it should work now.

**Comment by xiaoweiz** [comment]
@flying-sheep I had a successful installation from source with Homebrew before. I just thought I gave the binary installation a shot, which is obviously more convenient.

**Comment by flying-sheep** [comment]
as said: binary should work now :)

**Comment by JanSchulz** [comment]
@xiaoweiz if you have multiple R versions installed, could you send the output of the last line from these as well?

```
contrib.url(getOption("repos"), .Platform$pkgType)
```

I'm wondering if we don't have any mac users which download the package or if something changed between 3.1 and 3.2...

**Comment by xiaoweiz** [comment]
@JanSchulz I have only one R version installed, which is 3.2.
@flying-sheep Sorry to inform you that the binary installation still fails.... 

```
R
install.packages('rzmq', repos = 'http://irkernel.github.io/', type = 'mac.binary')
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://irkernel.github.io/bin/macosx/contrib/3.2

   package ‘rzmq’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘rzmq’ is not available (as a binary package for R version 3.2.0)
```

**Comment by JanSchulz** [comment]
Ok...

Can you do that once without any `type` parameter and once with `type=Platform$pkgType`?

**Comment by xiaoweiz** [comment]
Both give the same error message as above.

**Comment by JanSchulz** [comment]
Just to make sure because I didn't expect that: This:

```
install.packages('rzmq', repos = 'http://irkernel.github.io/', type = 'mac.binary.mavericks')
```

warns about 

```
Warning in install.packages :
  unable to access index for repository http://irkernel.github.io/bin/macosx/contrib/3.2
```
[path *without* `mavericks` in it?]

**Comment by xiaoweiz** [comment]
Ah, I didn't notice the minor difference. 
```R
install.packages('rzmq', repos = 'http://irkernel.github.io/', type = 'mac.binary.mavericks')
Warning: unable to access index for repository http://irkernel.github.io/bin/macosx/mavericks/contrib/3.2
```

```R
install.packages('rzmq', repos = 'http://irkernel.github.io/', type = 'mac.binary')
Warning: unable to access index for repository http://irkernel.github.io/bin/macosx/contrib/3.2
```

**Comment by igozali** [comment]
Hi, I was wondering why this issue is closed, as running the R commands to install IRkernel still results in the missing header error. If we still need rzmq or any zmq-related stuff, it would be nice if this was written in the requirements section of the README.md. 

```
> install.packages(c('rzmq','repr','IRkernel','IRdisplay'), 
    repos = c('http://irkernel.github.io/', getOption('repos')))
Installing packages into ‘/usr/local/lib/R/3.2/site-library’
(as ‘lib’ is unspecified)
trying URL 'http://irkernel.github.io/src/contrib/rzmq_0.7.7.tar.gz'
Content type 'application/octet-stream' length 897372 bytes (876 KB)
==================================================
downloaded 876 KB

trying URL 'http://irkernel.github.io/src/contrib/repr_0.4.tar.gz'
Content type 'application/octet-stream' length 11355 bytes (11 KB)
==================================================
downloaded 11 KB

trying URL 'http://irkernel.github.io/src/contrib/IRkernel_0.5.tar.gz'
Content type 'application/octet-stream' length 17951 bytes (17 KB)
==================================================
downloaded 17 KB

trying URL 'http://irkernel.github.io/src/contrib/IRdisplay_0.3.tar.gz'
Content type 'application/octet-stream' length 3385 bytes
==================================================
downloaded 3385 bytes

* installing *source* package ‘rzmq’ ...
** libs
clang++ -std=c++11 -I/usr/local/Cellar/r/3.2.3/R.framework/Resources/include -DNDEBUG -I/usr/local/include -I../inst/cppzmq -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include  -I/usr/local/include   -fPIC  -g -O2 -c interface.cpp -o interface.o
interface.cpp:22:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
         ^
1 error generated.
make: *** [interface.o] Error 1
ERROR: compilation failed for package ‘rzmq’
* removing ‘/usr/local/lib/R/3.2/site-library/rzmq’
* installing *source* package ‘repr’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (repr)
* installing *source* package ‘IRdisplay’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (IRdisplay)
ERROR: dependency ‘rzmq’ is not available for package ‘IRkernel’
* removing ‘/usr/local/lib/R/3.2/site-library/IRkernel’

The downloaded source packages are in
	‘/private/var/folders/s2/c_t0x85x0w9ffm8d001ppb0m0000gn/T/RtmpBPb3b5/downloaded_packages’
Warning messages:
1: In install.packages(c("rzmq", "repr", "IRkernel", "IRdisplay"),  :
  installation of package ‘rzmq’ had non-zero exit status
2: In install.packages(c("rzmq", "repr", "IRkernel", "IRdisplay"),  :
  installation of package ‘IRkernel’ had non-zero exit status
```

**Comment by janschulz** [comment]
irkernel master does not depend on rzmq anymore but on a zmw package which is on cran.

**Comment by takluyver** [comment]
Specifically, that package is [pbdZMQ](https://cran.r-project.org/web/packages/pbdZMQ/index.html).

**Comment by igozali** [comment]
Thanks for your replies! I'm still not sure what that means, since I'm very new to R. Does this mean I can just change "rzmq" to "zmw" in the list of packages that I'm installing?

**Comment by takluyver** [comment]
zmw was (I think) a typo for zmq. The library we're moving to is called pbdZMQ. But to use IRkernel with that, you need to install the development version from Github (the last release still uses rzmq, and this is what the instructions on the website get you to install).

There's an R package `devtools` which can install a package [from Github](http://www.inside-r.org/packages/cran/devtools/docs/install_github), but if you're new to R, it might be jumping in the deep end a bit.

**Comment by igozali** [comment]
Thanks! For regular or casual users of IRkernel, what would you recommend us to use? Naturally we would prefer stable releases, in which case, should we be aware to install zmq headers in our system?

**Comment by takluyver** [comment]
In general, yes, we would advise you to prefer stable releases. However, we're not really sure how to fix all the problems people have installing rzmq - that's why we're switching to pbdzmq, which will hopefully make things better. We need to get a new release out with that.
