### ISSUE TITLE
IRKernel - Notebook JSON is invalid

### ISSUE THREAD

**Issue by sirchuckles12** [IRkernel/IRkernel#551]
Any time I save an R notebook within JupyterLab (or Jupyter classic), I see the following error in the shell it is running.

Notebook JSON is invalid: Additional properties are not allowed ('source' was unexpected)
    
    Failed validating 'additionalProperties' in display_data:
    
    On instance['cells'][0]['outputs'][0]:
    {'data': {'image/png': 'iVBORw0KGgoAAAANSUhEUgAAA0gAAANICAYAAAD958/bAAAEDWlDQ1BJQ0MgUHJv...',
              'text/plain': 'plot without title'},
     'metadata': {},
     'output_type': 'display_data',
     'source': 'R display func'}

I see the same error on startup, if an R notebook is open when I start Jupyter. I'm not sure if this is a harmless (albeit annoying) problem or if the file is actually corrupted in some way.

Steps to reproduce:
1) Start a Jupyter/Jupyter Lab session and create a new R notebook
2) Run these things in a cell; 
test_data = data.frame(x = 1:10, y = 1:10)
plot(x=test_data$x, y = test_data$y)
3) Save the notebook

I am using IRKernel version 0.8.9

**Comment by takluyver** [comment]
I think this should have been fixed by #523 - can you try updating IRkernel?

**Comment by sirchuckles12** [comment]
That seemed to work on my Windows machine at home, but I'm still seeing this on other machines. Now I am using IRkernel 0.8.11

**Comment by takluyver** [comment]
If you saved notebooks with an older version of IRkernel, you'll need to rerun the cells causing the problem with the new version and then save it again in order to fix the notebook file.

**Comment by ckbhatt** [comment]
I am also seeing the same behaviour, notebook is working fine with classic notebook UI but failing with Jupyter Lab UI.
Is it because fix contained in https://github.com/IRkernel/IRkernel/pull/523 is not part of 0.8.11 and will come in the next release.
